### ISSUE TITLE
Schema validation for complex structure fails due to null downloader in URIManager class (final URIDownloader downloader = downloaders.get(scheme);)

### ISSUE THREAD

**Issue by biswakalyannayak** [fge/json-schema-validator#175]
com.github.fge.jsonschema.core.exceptions.ProcessingException: fatal: URI scheme "urn" not supported (URI: "urn:jsonschema:com:bk:datatypes:CodedData#")
    level: "fatal"
    scheme: "urn"
    uri: "urn:jsonschema:com:bk:datatypes:CodedData#"

	at com.github.fge.jsonschema.core.load.URIManager.getContent(URIManager.java:96)
	at com.github.fge.jsonschema.core.load.SchemaLoader$1.load(SchemaLoader.java:115)
	at com.github.fge.jsonschema.core.load.SchemaLoader$1.load(SchemaLoader.java:109)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
	at com.github.fge.jsonschema.core.load.SchemaLoader.get(SchemaLoader.java:172)
	at com.github.fge.jsonschema.core.load.RefResolver.rawProcess(RefResolver.java:114)
	at com.github.fge.jsonschema.core.load.RefResolver.rawProcess(RefResolver.java:51)
	at com.github.fge.jsonschema.core.processing.RawProcessor.process(RawProcessor.java:77)
	at com.github.fge.jsonschema.core.processing.RawProcessor.process(RawProcessor.java:41)
	at com.github.fge.jsonschema.core.processing.ProcessorChain$ProcessorMerger.process(ProcessorChain.java:189)
	at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
	at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:128)
	at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:120)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
	at com.github.fge.jsonschema.core.processing.CachingProcessor.process(CachingProcessor.java:109)
	at com.github.fge.jsonschema.processors.validation.ValidationChain.process(ValidationChain.java:107)
	at com.github.fge.jsonschema.processors.validation.ValidationChain.process(ValidationChain.java:57)
	at com.github.fge.jsonschema.core.processing.ProcessorMap$Mapper.process(ProcessorMap.java:166)
	at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
	at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:128)
	at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:120)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
	at com.github.fge.jsonschema.core.processing.CachingProcessor.process(CachingProcessor.java:109)
	at com.github.fge.jsonschema.processors.validation.InstanceValidator.process(InstanceValidator.java:110)
	at com.github.fge.jsonschema.processors.validation.InstanceValidator.processObject(InstanceValidator.java:218)
	at com.github.fge.jsonschema.processors.validation.InstanceValidator.process(InstanceValidator.java:151)
	at com.github.fge.jsonschema.processors.validation.InstanceValidator.processObject(InstanceValidator.java:218)
	at com.github.fge.jsonschema.processors.validation.InstanceValidator.process(InstanceValidator.java:151)
	at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:56)
	at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:34)
	at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
	at com.github.fge.jsonschema.main.JsonValidator.validate(JsonValidator.java:104)
	at com.bk.schema.util.JsonSchemaUtil.main(JsonSchemaUtil.java:100)

**Comment by biswakalyannayak** [comment]
private static final JsonValidator VALIDATOR = JsonSchemaFactory.byDefault().getValidator();
private static ObjectNode generateJsonSchemaForClass(Class<?> clazz) throws JsonMappingException {
    	ObjectMapper om = new ObjectMapper();
        SchemaFactoryWrapper vis = new SchemaFactoryWrapper();
        om.acceptJsonFormatVisitor(clazz, vis);
        JsonSchema schema = vis.finalSchema();
        JsonNode res = om.valueToTree(schema); // res has element "id":"urn:..."
        return (ObjectNode) res;
    }
public static void main(String[] args) {
    	JsonSchemaUtil util = new JsonSchemaUtil();
    	try {
ProcessingReport report  = VALIDATOR.validate(schema, json, false);
} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
   }

Above code generate the error.

**Comment by praetorian84** [comment]
I've run into the same issue. It seems that the schema output by the Jackson JSON Schema module uses this format of $ref for types that have been seen before, but that this type of $ref is not supported by the validator.

**Comment by biswakalyannayak** [comment]
Yes, I got some more inputs on this issue. if i use the example schema provided in test section to validate that work perfect. So it might be something when we create dynamic schema it fails because dynamic generated schema must be missing some detail information about the schema.
