### ISSUE TITLE
Conflict between json-schema-validator and jackson-core

### ISSUE THREAD

**Issue by shobr** [fge/json-schema-validator#188]
Hi,
I am getting below error when both jackson-core and json-schema-validator jars are used : 

java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:549)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:460)

I have seen that json-schema-validator does not have the above method in JsonFactory class while jackson-core has. 
Please provide a solution as I need to have both the jars in my classpath.

Thanks.

**Comment by huggsboson** [comment]
Which version of jackson are you including?  I read that error as something is expecting that method to be there and it isn't there, which usually happens when you have a newer version of a jar included and an older version.

http://stackoverflow.com/questions/27746750/exception-in-thread-main-java-lang-nosuchmethoderror-com-fasterxml-jackson-co

**Comment by shobr** [comment]
I am using jackson-2.7.4 and json-schema-validator-2.2.6.
In both these jars, above class is present but in json-schema-validatory, the method is not defined.

**Comment by huggsboson** [comment]
jackson-core 2.2.x is a transitive dependency of json-schema-validator, though it will probably work fine if you make sure jackson-core-2.7.x gets included due to backwards compatibility.

If you look at:
http://fasterxml.github.io/jackson-core/javadoc/2.2.0/com/fasterxml/jackson/core/JsonFactory.html
-and-
https://fasterxml.github.io/jackson-core/javadoc/2.7/com/fasterxml/jackson/core/JsonFactory.html

You'll notice that requiresPropertyOrdering isn't in 2.2 but is in 2.7.  So I'm assuming that somehow you're getting jackson-core 2.2 included in your classpath over 2.7.

**Comment by shobr** [comment]
Thanks @huggsboson 
So I changed jackson version from 2.7.4 to 2.2.3 and it works like a charm.

Also, I have another issue with json-schema-validator : 
http://stackoverflow.com/questions/38049997/json-schema-validator-not-validating-all-items-of-an-array-but-only-the-first-on

I don't know if I am doing something wrong.

**Comment by huggsboson** [comment]
Did you try the [deepCheck](http://fge.github.io/json-schema-validator/2.2.x/com/github/fge/jsonschema/main/JsonSchema.html#validate(com.fasterxml.jackson.databind.JsonNode, boolean)) option?  My reading of the docs makes me think it won't help you but it's worth trying.  Also you can probably remove a lot of extra nesting in your json's if you were so inclined by using oneOf.

**Comment by shobr** [comment]
I tried deep check option by setting it to true. Still same problem persists.

**Comment by huggsboson** [comment]
I'll try to check out the code but I'm in the middle of a crunch on a
separate project so probably can't promise a timeline on figuring iy out.
:(.

**Comment by shobr** [comment]
Hi,
Could you find time to check the code.

**Comment by xawyong** [comment]
Hi ,can anyone tell me which version of Jackson-core  is as  a transitive dependency for json-schema-validator-2.2.6-lib ?? thanks
